#!/usr/bin/env python3
"""Replace architecture diagram section using line-based boundaries."""
path = '/Users/a/Desktop/WorkSpace/ALL/我的Github项目/pi-deep-dive/pi/tutorial/pi-ai/pi-ai.md'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Find section boundaries
start_line = None
end_line = None
for i, line in enumerate(lines):
    if line.rstrip() == '## 整个包的分层图':
        start_line = i
    if start_line is not None and line.rstrip() == '```' and i > start_line + 3:
        # This is the closing ``` of the diagram
        # Check if this is the right one (not the opening ```)
        if lines[i-1].strip() == '' and i - start_line > 100:
            end_line = i
        elif i - start_line > 50:
            end_line = i

print(f'Section: lines {start_line}-{end_line}')

new_section = [
    '## 整个包的分层图\n',
    '\n',
    '`packages/ai/src` 按五层架构组织：\n',
    '\n',
    '```\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│                         对外入口层                                         │\n',
    '│                                                                         │\n',
    '│  index.ts       主入口 — 纯类型/工具/核心运行时导出，无副作用                │\n',
    '│  oauth.ts       OAuth 导出入口                                            │\n',
    '│  cli.ts         CLI 命令 (npx login / list)                              │\n',
    '│  compat.ts      旧版兼容入口 — 保留全局 stream()/complete() + env key 注入  │\n',
    '│  bedrock-provider.ts  Bedrock 桥接模块，避免主包直接依赖 @aws-sdk/*        │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│        第五层：models.ts — 统一 provider / models 运行时框架               │\n',
    '│                                                                         │\n',
    '│  ┌─ 文本聊天 ────────────────────┐  ┌─ 图片生成 ────────────────────┐   │\n',
    '│  │ models.ts                    │  │ images-models.ts              │   │\n',
    '│  │   createModels()             │  │   createImagesModels()        │   │\n',
    '│  │   createProvider()           │  │   createImagesProvider()      │   │\n',
    '│  │    每个请求:                  │  │ images-api-registry.ts        │   │\n',
    '│  │    ① 解析 auth               │  │ images.ts                     │   │\n',
    '│  │    ② 合并参数                 │  │   generateImages()            │   │\n',
    '│  │    ③ 分发给 owning provider  │  │                               │   │\n',
    '│  │   calculateCost()            │  │                               │   │\n',
    '│  │   clampThinkingLevel()       │  │                               │   │\n',
    '│  └──────────────────────────────┘  └───────────────────────────────┘   │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│            第四层：providers/ — Provider 装配注册层                        │\n',
    '│                                                                         │\n',
    '│  all.ts       → builtinProviders() / builtinModels()                     │\n',
    '│                 builtinImagesProviders() / builtinImagesModels()          │\n',
    '│  faux.ts      → 测试 Mock Provider (createFauxCore)                      │\n',
    '│                                                                         │\n',
    '│  每个 provider 文件做的事：模型目录(.models.ts) + 认证配置 + API 引擎        │\n',
    '│                                                  └─→ createProvider()    │\n',
    '│                                                                         │\n',
    '│  openai.ts           → openai-responses    │ anthropic.ts → anthropic-   │\n',
    '│  openai-codex.ts     → openai-codex        │               messages      │\n',
    '│  azure-openai*       → azure-openai        │ kimi-coding  → (同上)       │\n',
    '│                          -responses        │ minimax      → (同上)       │\n',
    '│  deepseek.ts         → openai-completions  │ minimax-cn   → (同上)       │\n',
    '│  openrouter.ts       → openai-completions  │ vercel-ai-   → (同上)       │\n',
    '│  groq.ts             → openai-completions  │   gateway                   │\n',
    '│  xai.ts              → openai-completions  │ fireworks    → 多引擎混合   │\n',
    '│  zai.ts              → openai-completions  │ github-      → 多引擎混合   │\n',
    '│  together.ts         → openai-completions  │   copilot                   │\n',
    '│  nvidia.ts           → openai-completions  │ opencode     → 多引擎混合   │\n',
    '│  cerebras.ts         → openai-completions  │ opencode-go  → 多引擎混合   │\n',
    '│  ...  共 36 个 provider (27 个用 openai-completions 引擎)                │\n',
    '│                                                                         │\n',
    '│  images/register-builtins.ts  → openrouter-images (图片)                 │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│              第三层：api/ — API 懒加载协议层                                │\n',
    '│                                                                         │\n',
    '│  懒加载基座:    lazy.ts          lazyApi() / lazyStream() 核心            │\n',
    '│               *.lazy.ts         各 API 模块的懒加载包装器                  │\n',
    '│                                                                         │\n',
    '│  协议实现:                                                                 │\n',
    '│    openai-completions.ts       OpenAI /v1/chat/completions              │\n',
    '│    openai-responses.ts         OpenAI /v1/responses                     │\n',
    '│    anthropic-messages.ts       Anthropic /v1/messages                   │\n',
    '│    google-generative-ai.ts     Google Gemini API                        │\n',
    '│    google-vertex.ts            Google Vertex AI                         │\n',
    '│    mistral-conversations.ts    Mistral API                              │\n',
    '│    bedrock-converse-stream.ts  AWS Bedrock ConverseStream               │\n',
    '│    azure-openai-responses.ts   Azure OpenAI Responses                   │\n',
    '│    openai-codex-responses.ts   OpenAI Codex Responses                   │\n',
    '│    openrouter-images.ts        图片生成 (OpenRouter)                     │\n',
    '│                                                                         │\n',
    '│  共享基座:                                                                 │\n',
    '│    openai-responses-shared.ts  Responses 系列共享：消息/工具转换、流处理    │\n',
    '│    transform-messages.ts       跨模型消息转换：thinking 降级/ID 归一化等    │\n',
    '│    google-shared.ts            Google 系列共享：Gemini/Vertex 消息转换     │\n',
    '│    simple-options.ts           SimpleStreamOptions → ProviderStreamOptions│\n',
    '│    openai-prompt-cache.ts      OpenAI 缓存 key 处理                       │\n',
    '│    cloudflare.ts / github-copilot-headers.ts  平台专用头部                 │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│                        认证与基础设施层                                    │\n',
    '│                                                                         │\n',
    '│  ┌─ auth/ 认证子系统 ────────────────────────────────────────────────┐  │\n',
    '│  │ types.ts          ProviderAuth / CredentialStore / AuthResult     │  │\n',
    '│  │ resolve.ts        resolveProviderAuth() 统一认证解析               │  │\n',
    '│  │                   (优先级: 显式覆盖 > 存储凭证 > 环境变量/ADC)       │  │\n',
    '│  │ credential-store.ts  InMemoryCredentialStore (可注入持久化)         │  │\n',
    '│  │ helpers.ts        envApiKeyAuth() / lazyOAuth()                   │  │\n',
    '│  │ context.ts        defaultProviderAuthContext()                    │  │\n',
    '│  │                                                                   │  │\n',
    '│  │ OAuth 子系统 (utils/oauth/):                                        │\n',
    '│  │ anthropic.ts / github-copilot.ts / openai-codex.ts                │\n',
    '│  │ device-code.ts / pkce.ts / oauth-page.ts / load.ts                │\n',
    '│  └───────────────────────────────────────────────────────────────────┘  │\n',
    '│                                                                         │\n',
    '│  ┌─ env-api-keys.ts 环境变量认证 ───────────────────────────────────┐   │\n',
    '│  │ findEnvKeys() / getEnvApiKey()  36 个 provider 的 env var 映射     │   │\n',
    '│  │ Vertex ADC / AWS Bedrock 多凭证源检测                               │   │\n',
    '│  └───────────────────────────────────────────────────────────────────┘  │\n',
    '│                                                                         │\n',
    '│  ┌─ utils/ 工具层 ──────────────────────────────────────────────────┐   │\n',
    '│  │ 流式引擎:    event-stream.ts   EventStream<T,R> 泛型 +            │   │\n',
    '│  │              AssistantMessageEventStream (可迭代 + result())       │   │\n',
    '│  │ 溢出检测:    overflow.ts       isContextOverflow()                 │   │\n',
    '│  │              60+ 正则覆盖 20+ provider                             │   │\n',
    '│  │ 重试:        retry.ts          isRetryableAssistantError()         │   │\n',
    '│  │              30+ 瞬态错误模式                                      │   │\n',
    '│  │ 校验:        validation.ts     validateToolCall()                  │\n',
    '│  │ Token:       estimate.ts       estimateContextTokens()             │\n',
    '│  │ 其他:        json-parse.ts / hash.ts / sanitize-unicode.ts /      │   │\n',
    '│  │              abort-signals.ts / deferred-tools.ts 等               │   │\n',
    '│  └───────────────────────────────────────────────────────────────────┘  │\n',
    '│                                                                         │\n',
    '│  session-resources.ts  会话资源生命周期管理                                │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│            第二层：模型信息生成层 (scripts/)                                 │\n',
    '│                                                                         │\n',
    '│  scripts/generate-models.ts        模型信息生成脚本 (构建时运行)            │\n',
    '│    → 从 models.dev / OpenRouter / AI Gateway 等源拉取模型数据             │\n',
    '│    → 补项目专属兼容元数据 (thinkingLevelMap / compat 等)                   │\n',
    '│    → 生成 models.generated.ts (36 个 provider)                           │\n',
    '│  scripts/generate-image-models.ts  图片模型生成脚本                        │\n',
    '│    → 生成 image-models.generated.ts                                      │\n',
    '│                                                                         │\n',
    '│  产物 (提交到 git):                                                       │\n',
    '│    models.generated.ts       36 个 provider 的静态模型合集                 │\n',
    '│    image-models.generated.ts 图片模型目录                                 │\n',
    '│    providers/*.models.ts     各 provider 的独立模型定义                   │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '                                   │\n',
    '                                   ▼\n',
    '┌─────────────────────────────────────────────────────────────────────────┐\n',
    '│              第一层：核心类型层 types.ts                                    │\n',
    '│                                                                         │\n',
    '│  全包核心类型定义 — 所有其他文件的基础                                      │\n',
    '│                                                                         │\n',
    '│  模型:      Model / ImagesModel / ModelCostRates / ModelThinkingLevel    │\n',
    '│  协议:      Api / KnownApi / ImagesApi / ProviderStreams                 │\n',
    '│  消息:      Message / AssistantMessage / ToolCall / ToolResultMessage    │\n',
    '│  事件:      AssistantMessageEvent (start / text_* / thinking_* /        │\n',
    '│             toolcall_* / done / error)                                  │\n',
    '│  上下文:    Context / ImagesContext                                       │\n',
    '│  工具:      Tool<TParameters>  TypeBox schema 绑定                       │\n',
    '│  选项:      StreamOptions / SimpleStreamOptions / ProviderStreamOptions  │\n',
    '│  兼容:      ModelCompat / OpenAICompletionsCompat / ProviderHeaders      │\n',
    '│  Provider:  KnownProvider / ProviderEnv / ProviderHeaders                │\n',
    '└─────────────────────────────────────────────────────────────────────────┘\n',
    '```\n',
]

# Replace: everything between "## 整个包的分层图" and the closing "```"
result = lines[:start_line] + new_section + lines[end_line+1:]

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(result)
print('DONE')
